sudo: required

language: generic

services:
  - docker

before_install:
    - docker build -t testimage .
    - docker run -d --rm --volume "${PWD}":/root --name testcontainer testimage

script:
    - docker exec -it testcontainer /bin/bash -c "cd /root; node generate.js"
    - docker exec -it testcontainer /bin/bash -c "cd /root; node difftest.js"
